### ISSUE TITLE
Implement sonar pulse

### ISSUE THREAD

**Issue by Csedge** [cs361w2019-osu/sprint1-project-group-14#48]

**Comment by staslyakhov** [comment]
**Story:** Sonar Pulse

As a player who dislikes guessing, I want there to be a sonar pulse ability that lets you reveal a portion of the opponents board so that I can ignore areas which don't contain enemy ships.

**Conversation:** 

After the a player sinks their first ship, the player should gain two charges of the sonar pulse ability, which can be used on the player's turn instead of an attack. A sonar pulse can be activated on any tile on the board, and it should reveal the location of all enemy ship tiles within a small area. The revealed tiles from the pulse should persist between players' turns.

**Confirmation:**

If an opponent's ship has no yet been sunk, the use of sonar pulse should fail.
If a player sinks a opponent's ship and uses sonar pulse twice, sonar pulse should fail for the rest of the game.
If a player uses sonar pulse on an opponent's board after sinking a ship, the location of ships in an area should be revealed.

**Estimated:** 1.5 hours

**Comment by Csedge** [comment]
Can you add a router called /sonar and then I will write the JS to help you integrate with it?

**Comment by staslyakhov** [comment]
I already wrote both the front and backend for the sonar. Check the feature branch.

**Comment by Csedge** [comment]
Ok open a pr for the feature  and then i will change the style for the button

**Comment by Csedge** [comment]
merge the #46 first and then merge your code...Your branch forgot the CSS.. I was update the style of the button.

**Comment by Aqcurate** [comment]
Implemented.
